import pytest
from core.signature import OriginMetadata, AISource

def test_analyze_code_style_gemini():
    content = "This code was generated by AGIO-CODEX for the system."
    meta = OriginMetadata.analyze_code_style(content)
    assert meta.source == AISource.GEMINI_CORE
    assert meta.style_hash is not None

def test_analyze_code_style_architect():
    content = "Approved by the Architect."
    meta = OriginMetadata.analyze_code_style(content)
    assert meta.source == AISource.HUMAN_ARCHITECT
    assert meta.style_hash is not None

def test_analyze_code_style_unknown():
    content = "Just some random python code print('hello')"
    meta = OriginMetadata.analyze_code_style(content)
    assert meta.source == AISource.UNKNOWN_ECHO
    assert meta.style_hash is not None

def test_analyze_code_style_gep_constitution():
    content = "import gep_constitution"
    meta = OriginMetadata.analyze_code_style(content)
    assert meta.source == AISource.GEMINI_CORE
