from agents.base_agent import BaseAgent
from core.envelope import AetherIntent

class AnalysisAgent(BaseAgent):
    def __init__(self, conductor):
        super().__init__("AnalysisAgent_001", conductor)

    async def request_economic_transaction(self):
        print("\n[Analysis] 📤 Requesting Economic Transaction...")
        await self.publish("aether.tasks.pending", AetherIntent.REQUEST_ACTION, {
            "tool_call": "economic_transaction",
            "amount": 100,
            "_security_context": "Authorized by Architect" # High trust signature
        })

    async def request_simulation_data(self):
        print("\n[Analysis] 📤 Requesting Simulation (High Risk)...")
        await self.publish("aether.tasks.pending", AetherIntent.REQUEST_ACTION, {
            "tool_call": "generate_simulation_data",
            "quality": "high",
            "_security_context": "Generated by AGIO-CODEX" # High trust signature
        })
